
CREATE TABLE IF NOT EXISTS ACTIVITY (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    ACTIVITY_NAME VARCHAR(50) NOT NULL,
    START_TIME TIMESTAMP NOT NULL,
    END_TIME TIMESTAMP NOT NULL,
    USER_ID BIGINT NOT NULL,
    FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID)
);

ALTER TABLE ACTIVITY
ADD COLUMN IF NOT EXITS USER_ID BIGINT NOT NULL;

ALTER TABLE ACTIVITY
ADD FOREIGN KEY IF NOT EXISTS (USER_ID) REFERENCES USER(USER_ID);


